### ISSUE TITLE
After clicking the indicator, the indicator remains selected

### ISSUE THREAD

**Issue by lee-dohm** [lee-dohm/soft-wrap-indicator#11]
## Repro Steps

1. Start Atom
1. Open a file
1. Click the soft wrap indicator to toggle the wrap mode

**Expected:** Underline on indicator to go away and focus to return to the editor
**Actual:** Underline remains and focus remains on the indicator

**Comment by skaraman** [comment]
I added this CSS to fix this issue - 

```css
.soft-wrap-indicator:focus {
	color: #b299b8;
}
.soft-wrap-indicator:focus.lit {
	color: #dfd5e2;
}
```
